package com.mir00r.jdbc_model;
// Generated Jul 17, 2016 1:10:41 AM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Employee generated by hbm2java
 */
//@Entity
public class Employee implements java.io.Serializable {
    //@Id
    private Integer id;
    private String name;
    private double salary;

    public Employee() {
    }

    public Employee(String name, double salary) {
        this.name = name;
        this.salary = salary;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getSalary() {
        return this.salary;
    }

    public void setSalary(double salary) {
        this.salary = salary;
    }

}
